from __future__ import annotations

"""Offline acceptance-v1 contracts. A red result is NOT a validator repair.

Only the real validator/repair run. Historical inputs are never reprojected.
New cases are synthetic derivatives, not additional model samples. Frozen
hashes cover input, expectation, and provenance; never update them at runtime.
"""

import ast
import hashlib
import importlib.util
import json
import os
import socket
import sqlite3
import sys
import tempfile
from copy import deepcopy
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from scripts import audit_line_model_validation_boundaries as audit  # noqa: E402

A = "absence_only_evidence_cannot_support_claim"
U = "unverifiable_limitation_claim"
PASS = ["pass"]
AUDIT_SHA = "774ffdb59fc0b30721c76aeb07c761460a75440fd34e588f422bfb4a000bbde0"
S1R_SHA = "b4b41ef6fbbb5210814f913b8a1fb2dd144a95e17199f9ec14ad013757522b78"
CORPORA = {
    "A": ("logs/line_model_shadow/final_phase_a_current_source_v2_20260830.jsonl", 20,
          "ab86c7e371a506f9d0f46084da04ac6f36f0c40d1c6bfd53136e5bedfe563125"),
    "B": ("logs/line_model_shadow/final_phase_b_current_source_v2_20260830.jsonl", 30,
          "95aac3d541d16948e01252c1fe524d4eb7c0eae94a53a7a2e1cdce8f99a9379b"),
}
LEGACY_TEST = "tests/test_line_model_shadow_service.py"
F1 = "test_deterministic_repair_only_removes_limitation_placeholders"
F2 = "test_deterministic_repair_generalizes_cited_event_id_and_required_day_threshold"
PE = "test_deterministic_repair_neutralizes_only_denied_relative_valuation_claim"
# Frozen once before the first pytest run; never regenerated by a test.
CASE_SHA256 = {
    "C01-A17": "ffadb59ee80da5ea58d40ac37fdc778a89de8c7a95c4d724c838e9473eff8725",
    "C01-B02": "f69ef01b162c150f42a1139b0c1c35d88b2901095855d219ee56c11821b40350",
    "C02-comparison": "ba0e0ff2eb48e3c84474db2a6a1efc7b17cb37fac5a692fcb60295ceb51cbb34",
    "C02-trend-tail": "26f83eb70accdae04b8289f70d6ee0d5bf3056b14ee49dc9f8e889f484c2a575",
    "C03-guard-inside": "06214b491521c84afd98416e3f8224ff3031ff3e1e1db45e4ac6ee5bd82b68cc",
    "C04-one-bullish": "e9129f759f1cefb607df06a10d48866c013c199c36c6da22daa9872b65dc6ef1",
    "C04-one-bearish": "1419e0c7f08863612c43e8f35ec17ca4739aca85c65013b9d24981a4f1c9016a",
    "C04-two-bullish": "9062d0ef36d6fb983609f153c4fe710dc2e7991fdb053b214b7a27d3d222249d",
    "C04-two-bearish": "87be0469470f896b73cb8b412f95c40acc2d60899f8075fa0e12038d3f43d8fd",
    "C04-unrelated-close-bullish": "d6d660bd956cfaef855e67899f76075747213a10ff12c5d115b3cbfcb6b711c8",
    "C04-unrelated-close-bearish": "6ccdc53c7a7eb269b838d6b6b07def3bdefc373d21f4b7beb2e297df8a035edc",
    "C05-broad-scope": "be1c57fd5d4cac2e96074ab8845d73eae51fde652c1cd414339cd527ec75d704",
    "C05-ok-limitation": "0866bace64d707eeddfeec200a9402cc7e002645fa9247f9ff1b89a59654d9b7",
    "C05-missing-text": "9204f7eb76f098fe6807b1fe8ad1e790fbc389a6744be0495a3ef98399864e41",
    "C06-text_template": "03897f7d7e248f2df7861a65a10210cd1fc8be7bd250f39c2711b81747f8fd17",
    "C06-conditions": "ca9c627883b125c8d36a1515b540cfe24bf5500428178a4b6444853c9e8690a5",
    "C06-missing_data": "314315414900c4a059af590b86f661abbfffd2e169b9363efa1c65d44ba3f740",
    "C06-research_limitations": "5f820f036a7b4e4a2a43c4ccbf40bbc5ece07fc3dc05db9ca3979d1fdf3ff074",
    "C07-text_template": "23865e89dc207e002ff53dd9ce001a1d4fae161a92ab357a50b19f6841ef2065",
    "C07-conditions": "f9eec7c8b7e6e00c0414bc93a6b916bfefbd96bc073cdc09dde691eb47f85392",
    "C07-missing_data": "49bc96a35c48f67683e735396c7898390f441af825a6f75899de1f2784b0bf4b",
    "C07-research_limitations": "78d505799d7e4d5208bc4522537043552b3246198142821aa0c6b94dce7ea44a",
    "C08-text_template": "42fc71551ef574634b3e43e051d98929744d1bf8a8d37dbdaf19a047bdf2417d",
    "C08-conditions": "9dfeb3246c37a0df524c3368a181b2638c8f5aec40e6e4daa9b33c2d6a3d1325",
    "C08-missing_data": "103cd2d96b471015cf2a1d492a0698a6307eee113571a5162fa0172920365978",
    "C08-research_limitations": "ecadc070ea2160d9e18aef1081f6ff9fb29b19a245c9ed7efb7bd1635d655079",
    "C09-recheck": "50eaa241287908b6e7f48a2dfc880e70e95208d78b2eaa0c5470c5975f350531",
    "C09-price-promise": "504e24d83af625400a030615a67a464ee8ab9ea189d6196162cbea66d1bc3398",
    "C10-equal": "75dc5429ce866e15ec2660974da26695698c4ee22933d563bec102dfe6aaa558",
    "C10-greater": "bc508be0558fa482927ae00f1cc9145236d58d4858c49960bdec34ad7b6f8a6e",
    "C10-negative": "428555d342e1baf0de0763607919fa4fde810543c27fc259036cb28408489695",
    "C10-zero-mean": "4838e5fcce55159d64cc803a292d32e6164a43e8c1b5220c6380d0fefdbc5b2e",
    "C10-nonfinite": "5efc89a2e370dfc95d238510f2ce8080492fb563f95353cc2fb711586a923eac",
    "C11-unit": "9962abaf59ad98394c31aa368d211c63336eccde7f78e83d342981611b169bae",
    "C11-trade-date": "56851ff31601382cfa568b146d47bb876d55e82f06ee11de5fa735f5fa37a502",
    "C11-missing-asof": "e25353cfe5c74f8eac71183f588df7f5a224434fd51f3d04c1f4b9b455f7132f",
    "C11-missing-trade-date": "8976cc73c72606eaf152089d105fe2d52aae20fd91b3ecc50d87c83517a856e9",
    "C11-wrong-field": "01e5e0613d549a759e9de12fc7bac959d1b4644948f25151579fa8a010e62ecf",
    "C12-missing-citation": "a380a0bf4abfb4eba3de1c9adde9b556302c5a60c0247dbba15db7ac698c9155",
    "C12-unknown-placeholder": "1443ecfcf9bc8071474925a320062d6f191a3273580ef94d15d41977840f9136",
    "C12-duplicate-fact": "938e0be5c7847b02c37330c94c0f8bbc92554bdabeee4f133ab22d1fb23e33a6",
    "C13-semicolon": "cb26e00201c15d2af89c8b047c5970751f28304fd50c63c475f7c373e2767b5d",
    "C13-period": "4fe486534ae6d4ac50c0d71db746bbe9ad4029be1e6d5ad407f68b6b2fdc9e95",
    "C13-newline": "d2633dbbd75882a1a128316dce7ed7bb37f3a5e7852f4c864320ef542f57a89d",
    "C13-contrast": "57372830b9f44a26fa42a5c58353d2879cd685f5b5cbcba5da2313b24722dc98",
    "C13-surface": "d13824693b65cfe79ab8381c0e22b03fc51afa6c2ceaae234cfcd2337ff16ee1",
    "C13-block": "d4c4bfa37a348611f07de9c527068595daedef27baaa0a5105a73d5e110ebbb1",
    "C14-significant-reduction": "809aec6081e0fbff5999e47a290a335c349f6353c805eff99d21ac99f2513843",
    "C14-yesterday": "66a53ae9a954de67038671e7eaa87710fddf3269fe2b572e00db570bfea7c0c5",
    "C15-suffix": "016a96e928b0afe5304fbed678297378258a70e7fec4d7d283285b26f65a6c60",
    "C15-prefix": "7ccb9c87570a49a1734056025475ec8c70140a8230523fec6483cbf024ae9ab7",
    "C15-conditions": "73a164c013081ffceacd3ade8dcb4050f0952fcb86202449c5ad2b70c6183bde",
    "C16-mixed": "1eca70d44a9cdfec6943ad3b068461f00ea7c137d6675b68e44e93cdae04c205",
    "C16-eligible-only-control": "be65e77e9c95f7b2839e395368ecfa8eaf6e822dd33e883d6c76d2a5475f914b",
    "C17-estimated": "2271bfa3330932dd36b00766ebae301c568d8a3f572f749b1f039b36b84ec41d",
    "C17-stale": "d178ec35bb8a971ead8139e27c8b1a443fe15589c2c166c17612415889eb92f0",
    "C17-source_delayed": "0f56bc4ddc1689ff6ca24ac1ef917b6b4e329d5d368feb2e747cde03ba61cbbe",
    "C18-other-block-cannot-authorize": "acda4a68895e0a9fdac8184264b1cf080b93777c9379dd58d03fc79e0d4263a5",
    "C18-unknown-code": "442fada0cf0319f62f6a6f5d57033fb0a0d7301264bc5b4e43e645b3f65f9f50",
    "C18-code-plus-direction": "f774e6f43bf77da24fe198f621ce4a1dfe3f73b129aa85ae419d80b9e471185d",
    "C19-missing-fact": "2a2f6517ecfcf5711fe892e51362ec8bf133ccd4f81dc39ced3897900410368d",
    "C19-missing-metadata": "dfc664d96b00dba2408b288607a9e834e62c6c99de0a4afe5332022351d61501",
    "C19-empty-general": "b738cefb4110faa19679b1399c4e135ccb1273906134d91622cf34eb5c2164dc",
    "C20-a-u-a": "fc83792ecf753a44111b21bb16e3dda4e57d15d6ee36bb80f4c0bda92a9b8594",
    "C20-u-a-u": "ce15c22d508368dd519c3e207075fae0f396cb48a4f18c729c04d90ce4ba6614",
    "C21-F1-original": "03dc2ee7670bd5a7c96925ccd4442f2b258ea307642f29481be5f23f88e63faa",
    "C21-F1-synthetic-positive": "3c05005abd7aa73d7e83bafbbed7ecc5cdea22a82fdc3fe44e466aac7f239b6e",
    "C21-F2-original": "0641a06143582b0f23cee1d47576fced674bb1b45353fb6885c8c8bc711014c6",
    "C21-F2-synthetic-positive": "4500ac12fb858adf0f338a218b00a8dbe4eddec87dd5daefbc06756676918a5f",
    "C21-PE-original": "20e19cf063d752570b8fbce12e9e488f8023ec681832c02be120f3bece8d5db5"
}


def digest(value):
    return hashlib.sha256(json.dumps(value, ensure_ascii=False, sort_keys=True,
                                   separators=(",", ":"), allow_nan=False).encode()).hexdigest()


def load_corpus(label):
    path, count, sha = CORPORA[label]
    data = (ROOT / path).read_bytes()
    assert hashlib.sha256(data).hexdigest() == sha, f"corpus drift: {path}"
    rows = [json.loads(line) for line in data.decode("utf-8-sig").splitlines()]
    assert len(rows) == count
    assert [row["attempt_index"] for row in rows] == list(range(1, count + 1))
    return rows


def legacy_fixture(name):
    """Read literal packet/output assignments, not a copied second fixture source."""
    tree = ast.parse((ROOT / LEGACY_TEST).read_text(encoding="utf-8"))
    function, = [node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == name]
    values = {}
    for node in function.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Name) and target.id in {"packet", "output"}:
                assert target.id not in values, "ambiguous fixture assignment"
                values[target.id] = ast.literal_eval(node.value)
    assert set(values) == {"packet", "output"}
    return values, {"file": LEGACY_TEST, "function": name, "line": function.lineno,
                    "file_sha256": hashlib.sha256((ROOT / LEGACY_TEST).read_bytes()).hexdigest(),
                    "literal_input_sha256": digest(values)}


def literal_renderings(packet, output):
    """Expected positive text only; does not decide eligibility or call production."""
    facts = {fact["fact_id"]: fact for fact in packet["facts"]}
    result = []
    for block in output["explanation_blocks"]:
        text = block["text_template"]
        for fact_id, fact in facts.items():
            unit = {"TWD": " 元", "shares": " 股", "ratio": " 倍", "": ""}.get(fact.get("unit", ""), "")
            value = str(fact["value"])
            # Canonical renderer drops a nonsemantic .0 for integral floats.
            # Keep fractional values and source strings exact; never round.
            if isinstance(fact["value"], float) and fact["value"].is_integer():
                value = str(int(fact["value"]))
            if fact.get("quality") == "estimated":
                value = "推估 " + value
            text = text.replace("{{" + fact_id + "}}", value + unit)
        result.append(text)
    return result


def build_compatibility_cases():
    assert hashlib.sha256((ROOT / "scripts/audit_line_model_validation_boundaries.py").read_bytes()).hexdigest() == AUDIT_SHA
    assert hashlib.sha256((ROOT / "tests/test_line_model_absence_only_release_contract.py").read_bytes()).hexdigest() == S1R_SHA
    originals = {case["case_id"]: case for case in audit.build_cases()}
    base = originals["honest_limitation:text_template"]
    cases = []
    source_inputs = {}

    def make(case_id, text=None, surface="text_template", expected=None, source=None):
        source = source or base
        case = {"case_id": case_id, "surface": surface, "packet": deepcopy(source["packet"]),
                "output": deepcopy(source["output"]), "expected_raw": list(expected or PASS),
                "expected_after_repair": list(expected or PASS), "expected_repair_codes": [],
                "provenance": {"kind": "synthetic_derivative", "audit_source_sha256": AUDIT_SHA,
                               "source_case_id": source["case_id"], "source_case_sha256": digest(source)}}
        if text is not None:
            if surface == "text_template":
                case["output"]["explanation_blocks"][0][surface] = text
            elif surface == "conditions":
                case["output"]["explanation_blocks"][0][surface] = [text]
            else:
                case["output"][surface] = [text]
        cases.append(case)
        source_inputs[case_id] = deepcopy({key: source[key] for key in ("packet", "output")})
        return case

    def block(case):
        return case["output"]["explanation_blocks"][0]

    def fact(case, fact_id):
        matches = [f for f in case["packet"]["facts"] if f["fact_id"] == fact_id]
        assert len(matches) == 1
        return matches[0]

    def volume(case_id, label="A", attempt=17, block_index=3, expected=None, comparison_only=False):
        row = load_corpus(label)[attempt - 1]
        result = row["body"]["result"]
        original_text = json.loads(result["model_output"])["explanation_blocks"][block_index - 1]["text_template"]
        start = original_text.index("當日成交量")
        text = original_text[start:]
        if comparison_only:
            text = text.split("，", 1)[0] + "。"
        case = make(case_id, "支撐壓力資料不足。" + text, expected=expected)
        ids = ["F043" if label == "B" and attempt == 14 else "F006", "F030"]
        for fid in ids:
            selected, = [f for f in result["compacted_packet"]["facts"] if f["fact_id"] == fid]
            case["packet"]["facts"].append(deepcopy(selected))
        block(case)["evidence_ids"] = ["F101", *ids]
        case["provenance"].update(corpus=CORPORA[label][0], corpus_sha256=CORPORA[label][2],
                                  attempt=attempt, block=block_index, original_text=original_text,
                                  selected_span=[start, len(original_text)], selected_fact_ids=ids)
        return case

    volume("C01-A17")
    volume("C01-B02", "B", 2, 4)
    volume("C02-comparison", "B", 14, 4, comparison_only=True)
    volume("C02-trend-tail", "B", 14, 4, expected=[U])

    comparison = make("C03-guard-inside", source=originals["grounded_comparison"])
    block(comparison).update(block_type="limitation", evidence_ids=["F101", "F102", "F103"])
    block(comparison)["text_template"] = "支撐壓力資料不足。" + block(comparison)["text_template"]
    for fid, domain in (("F102", "official_ohlcv"), ("F103", "technical")):
        fact(comparison, fid).update(domain=domain, trade_date="2026-08-28")

    for configuration in ("one", "two", "unrelated-close"):
        for direction, text in (("bullish", "均線結構偏多。"), ("bearish", "價格趨勢已轉弱。")):
            case = make(f"C04-{configuration}-{direction}", "支撐壓力資料不足；" + text, expected=[A])
            if configuration != "one":
                extra = deepcopy(base["packet"]["facts"][0] if configuration == "two"
                                 else originals["grounded_comparison"]["packet"]["facts"][1])
                extra["fact_id"] = "F104"
                case["packet"]["facts"].append(extra)
                block(case)["evidence_ids"].append("F104")

    for variant in ("broad-scope", "ok-limitation", "missing-text"):
        case = make(f"C05-{variant}", "均線結構偏多。", expected=[A])
        change = {"broad-scope": {"use_scope": ["limitation", "explanation"]},
                  "ok-limitation": {"quality": "ok"},
                  "missing-text": {"quality": "missing", "value": "均線結構偏多"}}[variant]
        fact(case, "F101").update(change)

    for family, text, expected in (
        ("C06", "資料不足，無法判斷是否偏多。", PASS),
        ("C07", "無法判斷支撐壓力，但均線已轉弱。", [A]),
        ("C08", "資料不足，並非不能判斷偏多。", [U]),
    ):
        for surface in audit.SURFACES:
            make(f"{family}-{surface}", text, surface, expected)
    make("C09-recheck", "若資料補齊，再評估支撐壓力。")
    make("C09-price-promise", "若資料補齊，股價就會上漲。", expected=[A])

    for variant in ("equal", "greater", "negative", "zero-mean", "nonfinite"):
        case = volume(f"C10-{variant}", expected=[U])
        v, m = fact(case, "F006"), fact(case, "F030")
        if variant == "equal":
            v["value"] = m["value"]
        elif variant == "greater":
            v["value"] = "22143103"
        elif variant == "negative":
            v["value"] = "-1"
        elif variant == "zero-mean":
            m["value"] = "0"
        else:
            v["value"] = "NaN"  # JSON string, never a nonstandard JSON NaN literal.
    for variant in ("unit", "trade-date", "missing-asof", "missing-trade-date", "wrong-field"):
        case = volume(f"C11-{variant}", expected=[U])
        m = fact(case, "F030")
        if variant == "unit":
            m["unit"] = "TWD"
        elif variant == "trade-date":
            m["trade_date"] = "2026-08-27"
        elif variant == "missing-asof":
            m.pop("as_of")
        elif variant == "missing-trade-date":
            m.pop("trade_date")
        else:
            m["field"] = "close"
    for variant in ("missing-citation", "unknown-placeholder", "duplicate-fact"):
        case = volume(f"C12-{variant}", expected=[U])
        if variant == "missing-citation":
            block(case)["evidence_ids"].remove("F030")
        elif variant == "unknown-placeholder":
            block(case)["text_template"] = block(case)["text_template"].replace("{{F030}}", "{{F999}}")
        else:
            extra = deepcopy(fact(case, "F030"))
            extra["value"] = "0"
            case["packet"]["facts"].append(extra)

    for variant, separator in (("semicolon", "；"), ("period", "。"), ("newline", "\n"),
                               ("contrast", "，但是"), ("surface", None), ("block", None)):
        case = volume(f"C13-{variant}", expected=[U])
        text = block(case)["text_template"]
        if separator is not None:
            block(case)["text_template"] = text.replace("，量能", separator + "量能", 1)
        else:
            head, tail = text.split("，量能", 1)
            block(case)["text_template"] = head + "。"
            if variant == "surface":
                block(case)["conditions"] = ["量能" + tail]
            else:
                case["output"]["explanation_blocks"][1].update(
                    text_template="量能" + tail, evidence_ids=["F101", "F006", "F030"])
    for variant, tail in (("significant-reduction", "量能顯著縮減"), ("yesterday", "量能較昨日縮減")):
        case = volume(f"C14-{variant}", expected=[U])
        block(case)["text_template"] = block(case)["text_template"].replace("量能未顯著放大", tail)
    for variant in ("suffix", "prefix", "conditions"):
        case = volume(f"C15-{variant}", expected=[A])
        if variant == "suffix":
            block(case)["text_template"] += "但均線結構偏多。"
        elif variant == "prefix":
            block(case)["text_template"] = "均線結構偏多。" + block(case)["text_template"]
        else:
            block(case)["conditions"] = ["均線結構偏多。"]

    for variant in ("mixed", "eligible-only-control"):
        case = make(f"C16-{variant}", "均線結構偏多。", expected=[U] if variant == "mixed" else PASS)
        case["packet"]["facts"].append({"fact_id": "F104", "domain": "technical", "field": "trend",
                                         "value": "偏多", "authority_tier": "canonical_db", "quality": "ok",
                                         "use_scope": ["explanation"]})
        block(case)["evidence_ids"] = ["F101", "F104"] if variant == "mixed" else ["F104"]
        if variant != "mixed":
            block(case)["block_type"] = "inference"
    for quality in ("estimated", "stale", "source_delayed"):
        case = volume(f"C17-{quality}", expected=PASS if quality == "estimated" else [U])
        for fid in ("F006", "F030"):
            fact(case, fid)["quality"] = quality

    case = make("C18-other-block-cannot-authorize", "均線結構偏多。", "missing_data", [A],
                source=originals["grounded_comparison"])
    make("C18-unknown-code", "unmapped_domain", "research_limitations", [U])
    case = make("C18-code-plus-direction", "fundamentals；均線結構偏多。", "missing_data", [A])
    case["packet"]["facts"].append({"fact_id": "F104", "domain": "fundamentals", "field": "availability",
                                     "quality": "unavailable", "value": None, "authority_tier": "canonical_db",
                                     "use_scope": ["limitation"]})
    for variant in ("missing-fact", "missing-metadata", "empty-general"):
        case = make(f"C19-{variant}", "資料不足" if variant == "empty-general" else "支撐資料不可用。",
                    expected=PASS if variant == "empty-general" else [U])
        if variant == "missing-metadata":
            fact(case, "F101").pop("field")
        else:
            case["packet"]["facts"] = []
            for index, b in enumerate(case["output"]["explanation_blocks"]):
                b["evidence_ids"] = []
                if index:
                    b["text_template"] = "資料不足"

    for variant, reasons, texts in (
        ("a-u-a", [A, U], ["均線結構偏多。", "未定義的分析尾句。", "均線結構偏多。"]),
        ("u-a-u", [U, A], ["未定義的分析尾句。", "均線結構偏多。", "未定義的分析尾句。"]),
    ):
        case = make(f"C20-{variant}", expected=reasons)
        for b, text in zip(case["output"]["explanation_blocks"], texts):
            b["text_template"] = text

    for label, function in (("F1", F1), ("F2", F2), ("PE", PE)):
        source, provenance = legacy_fixture(function)
        for variant in (("original", "synthetic-positive") if label != "PE" else ("original",)):
            case = make(f"C21-{label}-{variant}")
            case.update(deepcopy(source))
            source_inputs[case["case_id"]] = deepcopy(source)
            case["provenance"] = {"kind": "existing_synthetic_fixture" if variant == "original"
                                  else "synthetic_derivative", "legacy": provenance}
            case["expected_after_repair"] = [U] if variant == "original" and label != "PE" else PASS
            if variant == "synthetic-positive":
                if label == "F1":
                    case["packet"]["facts"][0].update(domain="support_resistance", field="availability")
                else:
                    case["output"]["research_limitations"] = ["事件尚未驗證"]

    # Exact old-priority reasons observed in draft_pre_freeze_probe.json. These
    # are constants, not selected from the validator result while testing.
    old_priority = {
        "C12-missing-citation": (["placeholder_without_matching_evidence", "unresolved_placeholder"],
                                 ["placeholder_without_matching_evidence", "unresolved_placeholder"], []),
        "C12-unknown-placeholder": (["comparison_without_two_numeric_placeholders", "placeholder_without_matching_evidence", "unresolved_placeholder"],
                                    ["comparison_without_two_numeric_placeholders", "placeholder_without_matching_evidence", "unresolved_placeholder"], []),
    }
    for quality in ("stale", "source_delayed"):
        old_priority[f"C17-{quality}"] = (["ineligible_numeric_placeholder", "unresolved_placeholder"],
                                          ["comparison_without_two_numeric_placeholders"], ["removed_absence_placeholder"])
    for variant in ("original", "synthetic-positive"):
        old_priority[f"C21-F1-{variant}"] = (["ungrounded_numeric_or_date_claim", "ineligible_numeric_placeholder", "unresolved_placeholder"],
                                             [U] if variant == "original" else PASS,
                                             ["removed_absence_placeholder", "removed_event_placeholder"])
        old_priority[f"C21-F2-{variant}"] = (["ungrounded_numeric_or_date_claim"],
                                             [U] if variant == "original" else PASS,
                                             ["generalized_cited_event_id", "generalized_required_day_threshold"])
    old_priority["C21-PE-original"] = (["missing_fact_used_outside_limitation", "relative_valuation_without_baseline"],
                                       PASS, ["reclassified_limitation_evidence_block", "neutralized_denied_relative_valuation_terms"])
    repaired_positives = {
        "C21-F1-synthetic-positive": ["支撐資料 不可用，事件 尚未驗證。"],
        "C21-F2-synthetic-positive": ["近期事件仍待驗證，資料需累積至所需交易日門檻。"],
        "C21-PE-original": ["本益比為28.05 倍；缺乏比較基準，無法判斷相對估值或相對估值。"],
    }
    for case in cases:
        if case["case_id"] in old_priority:
            raw, after, codes = old_priority[case["case_id"]]
            case.update(expected_raw=raw, expected_after_repair=after, expected_repair_codes=codes)
        case["provenance"]["derivation"] = {
            "packet_sha256": digest(case["packet"]), "output_sha256": digest(case["output"]),
            "changes": input_changes(source_inputs[case["case_id"]], {key: case[key] for key in ("packet", "output")}),
            "note": "Changes are relative to the named audit/legacy fixture. Historical numeric facts retain their source metadata.",
        }
        case["expected_rendered_raw"] = literal_renderings(case["packet"], case["output"]) if case["expected_raw"] == PASS else []
        case["expected_rendered_after_repair"] = deepcopy(case["expected_rendered_raw"]) if case["expected_after_repair"] == PASS else []
        if case["case_id"] in repaired_positives:
            case["expected_rendered_after_repair"] = repaired_positives[case["case_id"]]
    return cases


def input_changes(before, after, path=""):
    """A readable exact change list, not a vague 'fixture adjusted' label."""
    if isinstance(before, dict) and isinstance(after, dict):
        changes = []
        for key in sorted(set(before) | set(after)):
            if key not in before or key not in after:
                changes.append({"path": path + "/" + key, "before_present": key in before,
                                "after_present": key in after, "before": before.get(key), "after": after.get(key)})
            else:
                changes.extend(input_changes(before[key], after[key], path + "/" + key))
        return changes
    if before != after:
        return [{"path": path, "before": before, "after": after}]
    return []


def frozen_cases(cases):
    ids = [case["case_id"] for case in cases]
    assert len(ids) == len(set(ids)) == len(CASE_SHA256), "case count/duplicate drift"
    assert set(ids) == set(CASE_SHA256), "case identity drift"
    for case in cases:
        assert digest(case) == CASE_SHA256[case["case_id"]], f"case content drift: {case['case_id']}"
    return {case["case_id"]: case for case in cases}


@pytest.fixture(autouse=True)
def forbid_external_io(monkeypatch):
    attempts = []

    def forbidden(*_args, **_kwargs):
        attempts.append("external_io_attempt")
        raise AssertionError("offline compatibility tests must not access network or DB")

    monkeypatch.setattr(socket.socket, "connect", forbidden)
    monkeypatch.setattr(socket.socket, "connect_ex", forbidden)
    monkeypatch.setattr(socket, "create_connection", forbidden)
    monkeypatch.setattr(sqlite3, "connect", forbidden)
    yield
    assert attempts == []


@pytest.fixture(scope="module")
def evidence_directory(tmp_path_factory):
    configured = os.environ.get("ABSENCE_COMPAT_EVIDENCE_DIR")
    if not configured:
        return tmp_path_factory.mktemp("absence-compat")
    parent = Path(configured)
    if not parent.is_absolute():
        parent = ROOT / parent
    parent.mkdir(parents=True, exist_ok=True)
    return Path(tempfile.mkdtemp(prefix="compat-", dir=parent))


def write_evidence(directory, name, row):
    with (directory / (name + ".json")).open("x", encoding="utf-8") as stream:
        json.dump(row, stream, ensure_ascii=False, indent=2, allow_nan=False)
        stream.write("\n")
        stream.flush()
        os.fsync(stream.fileno())


def evaluate_input(packet, output):
    """Actual raw and diagnostic repair; service-final selection stays separate."""
    before = digest({"packet": packet, "output": output})
    row = {}
    try:
        raw = audit.validate_model_analysis_v2(output, packet)
        row["raw"] = asdict(raw)
        repaired, codes = audit.deterministic_limitation_placeholder_repair(output, packet)
        row["repair_codes"] = list(codes)
        row["after_repair_output"] = deepcopy(repaired)
        after = audit.validate_model_analysis_v2(repaired if repaired is not None else output, packet)
        row["after_repair"] = asdict(after)
        # Match execute_line_model_shadow: rejected repair remains diagnostic;
        # only a PASSED repair replaces the raw verdict/reasons in service output.
        repair_attempted = not raw.passed and repaired is not None and bool(codes)
        use_repair = repair_attempted and after.passed
        row["service_final"] = asdict(after if use_repair else raw)
        row["service_repair_attempted"] = repair_attempted
        row["service_used_repair"] = use_repair
    except Exception as exc:
        row["exception"] = {"type": type(exc).__name__, "message": str(exc)}
    row["input_unchanged"] = before == digest({"packet": packet, "output": output})
    return row


def verdict_errors(result, expected_reasons, expected_rendered):
    errors = []
    expected_pass = expected_reasons == PASS
    if result["passed"] is not expected_pass:
        errors.append(f"passed={result['passed']!r}, expected={expected_pass}")
    if list(result["reason_codes"]) != expected_reasons:
        errors.append(f"reasons={result['reason_codes']!r}, expected={expected_reasons!r}")
    if list(result["rendered_blocks"]) != expected_rendered:
        errors.append(f"rendered={result['rendered_blocks']!r}, expected={expected_rendered!r}")
    return errors


@pytest.fixture(scope="module")
def pinned_cases(evidence_directory):
    cases = frozen_cases(build_compatibility_cases())
    write_evidence(evidence_directory, "manifest", {
        "captured_at": datetime.now(timezone.utc).isoformat(), "cases": list(cases.values()),
        "case_sha256": CASE_SHA256, "validator_sha256": hashlib.sha256(
            (ROOT / "review_src/core/line_model_validation.py").read_bytes()).hexdigest(),
        "test_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
    })
    return cases


@pytest.mark.parametrize("case_id", tuple(CASE_SHA256))
def test_absence_compatibility_contract(case_id, pinned_cases, evidence_directory):
    case = deepcopy(pinned_cases[case_id])
    evidence = evaluate_input(case["packet"], case["output"])
    errors = []
    if "exception" in evidence:
        errors.append(f"unexpected exception: {evidence['exception']}")
    else:
        for stage in ("raw", "after_repair"):
            errors.extend(f"{stage}: {error}" for error in verdict_errors(
                evidence[stage], case[f"expected_{stage}"], case[f"expected_rendered_{stage}"]))
        if evidence["repair_codes"] != case["expected_repair_codes"]:
            errors.append(f"repair code drift: {evidence['repair_codes']}")
    if not evidence["input_unchanged"] or digest(case) != CASE_SHA256[case_id]:
        errors.append("input changed")
    write_evidence(evidence_directory, case_id, {
        "case": case, "observed": evidence, "contract_errors": errors,
        "contract_passed": not errors, "model_calls": 0, "db_calls": 0,
        "valid_for_live_quality_or_load_matrix": False,
    })
    assert not errors, f"{case_id}; evidence={evidence_directory / (case_id + '.json')}\n" + "\n".join(errors)


@pytest.mark.parametrize("label,attempt", [(label, i) for label, (_, count, _) in CORPORA.items()
                                         for i in range(1, count + 1)])
def test_preserved_historical_baseline_replay(label, attempt, evidence_directory):
    original = load_corpus(label)[attempt - 1]
    before = digest(original)
    result = original["body"]["result"]
    packet = result["compacted_packet"]
    baseline = evaluate_input(packet, result["model_output"])
    try:
        stored = asdict(audit.validate_model_analysis_v2(
            result.get("validated_model_output") or result["model_output"], packet))
    except Exception as exc:
        stored = {"exception": {"type": type(exc).__name__, "message": str(exc)}}
    historical = {key: result.get(key) for key in (
        "raw_validator_result", "raw_validator_reason_codes", "validator_result",
        "validator_reason_codes", "deterministic_repair_codes", "rendered_blocks")}
    write_evidence(evidence_directory, f"historical-{label}{attempt:02}", {
        "original_record": original, "H": historical, "B": baseline,
        "stored_validated_output_replay": stored, "C": None,
        "candidate_status": "not_implemented_not_authorized",
        "input_unchanged": digest(original) == before,
        "model_calls": 0, "valid_for_live_quality_or_load_matrix": False,
        "validator_sha256": hashlib.sha256((ROOT / "review_src/core/line_model_validation.py").read_bytes()).hexdigest(),
    })
    assert "exception" not in baseline, baseline.get("exception")
    assert "exception" not in stored, stored.get("exception")
    assert baseline["input_unchanged"] and digest(original) == before


@pytest.mark.parametrize("mutation", ["missing", "duplicate", "unknown", "text", "packet", "expected"])
def test_compatibility_manifest_rejects_drift(mutation):
    cases = build_compatibility_cases()
    target = cases[0]
    if mutation == "missing":
        cases.pop()
    elif mutation == "duplicate":
        cases[1]["case_id"] = target["case_id"]
    elif mutation == "unknown":
        target["case_id"] = "unknown-case"
    elif mutation == "text":
        target["output"]["explanation_blocks"][0]["text_template"] = "資料不足。"
    elif mutation == "packet":
        target["packet"]["facts"][0]["quality"] = "ok"
    else:
        target["expected_raw"] = ["invalid_json"]
    with pytest.raises(AssertionError, match="drift"):
        frozen_cases(cases)


@pytest.mark.parametrize("result,expected", [
    ({"passed": False, "reason_codes": ["invalid_json"], "rendered_blocks": []}, [A]),
    ({"passed": False, "reason_codes": [A + "_typo"], "rendered_blocks": []}, [A]),
    ({"passed": False, "reason_codes": [A, "invalid_block_schema"], "rendered_blocks": []}, [A]),
    ({"passed": True, "reason_codes": [A], "rendered_blocks": []}, [A]),
    ({"passed": False, "reason_codes": [A], "rendered_blocks": ["均線結構偏多"]}, [A]),
    ({"passed": False, "reason_codes": [U, A], "rendered_blocks": []}, [A, U]),
])
def test_compatibility_verdict_rejects_false_green(result, expected):
    assert verdict_errors(result, expected, [])


def test_compatibility_verdict_checks_full_positive_rendering():
    result = {"passed": True, "reason_codes": PASS, "rendered_blocks": ["收盤100 元"]}
    assert verdict_errors(result, PASS, ["收盤100 元高於均線90 元。"])
    assert not verdict_errors(result, PASS, ["收盤100 元"])


def test_replay_final_selection_matches_real_service_when_repair_is_rejected(monkeypatch, tmp_path, evidence_directory):
    """Mock transport ONLY; exercise actual packet builder, service, validator, repair."""
    existing = ROOT / "tests/test_line_model_v2_contracts.py"
    spec = importlib.util.spec_from_file_location("compat_existing_v2_contracts", existing)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    monkeypatch.setenv("LINE_MODEL_RESEARCH_ROLLOUT", "off")
    monkeypatch.setenv("LINE_MODEL_SHADOW_IDLE_GRACE_MS", "0")
    monkeypatch.setenv("QWEN_CONTEXT_TOKENS", "16384")
    monkeypatch.setenv("QWEN_MAX_OUTPUT_TOKENS", "900")
    monkeypatch.delenv("LINE_MODEL_V2_PROFILE", raising=False)

    def repair_still_rejected(packet):
        output = module._grounded_missing_data_output(packet)
        first = output["explanation_blocks"][0]
        first["block_type"] = "inference"
        first["text_template"] += "引用為{{F999}}。"
        return output

    result = module._run_offline_v2_contract(monkeypatch, tmp_path, "compat-repair-final-selection", repair_still_rejected)
    observed = evaluate_input(result["compacted_packet"], result["model_output"])
    write_evidence(evidence_directory, "service-final-selection", {
        "actual_service_result": result, "offline_replay": observed,
        "model_transport": "synthetic_QwenChatResult", "real_model_calls": 0,
        "service_source_sha256": hashlib.sha256((ROOT / "review_src/services/line_model_shadow_service.py").read_bytes()).hexdigest(),
    })
    assert observed["service_repair_attempted"] is True
    assert observed["service_used_repair"] is False
    assert observed["after_repair"]["passed"] is False
    assert observed["raw"]["reason_codes"] != observed["after_repair"]["reason_codes"]
    assert list(observed["service_final"]["reason_codes"]) == result["validator_reason_codes"]
    assert result["validator_reason_codes"] == result["raw_validator_reason_codes"]
    assert result["candidate_can_replace_reply"] is False
