from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REVIEW_SRC = ROOT / "review_src"
if str(REVIEW_SRC) not in sys.path:
    sys.path.insert(0, str(REVIEW_SRC))

from core.outlook_context import apply_holiday_dampener, make_factor_freshness
from market.calendar_override import apply_override, clear_expired_overrides, get_active_override
from market.calendar_status import get_next_twse_trading_day_after
from market.calendar_status import get_market_calendar_status
from outlook.shadow_builder import build_shadow_outlook_context


def _context(code: str, iso_time: str) -> dict:
    return build_shadow_outlook_context(code, datetime.fromisoformat(iso_time)).to_dict()


def _override_examples() -> tuple[dict, dict]:
    active = apply_override(
        "TWSE",
        "2026-07-24",
        "typhoon_closed",
        "shadow test typhoon closure",
        expires_at="2026-07-25T00:00:00+08:00",
        created_by="shadow_export",
    )
    active_status = get_market_calendar_status("TWSE", datetime.fromisoformat("2026-07-24T10:00:00+08:00"))
    active_payload = {
        "override": active.to_dict(),
        "active_override": get_active_override(
            "TWSE",
            "2026-07-24",
            as_of_time=datetime.fromisoformat("2026-07-24T10:00:00+08:00"),
        ).to_dict(),
        "status": active_status.to_dict(),
        "note": "Process-local in-memory override only; no DB write and no production takeover.",
    }

    expired = apply_override(
        "TWSE",
        "2026-07-25",
        "closed",
        "expired shadow test override",
        expires_at="2026-07-24T00:00:00+08:00",
        created_by="shadow_export",
    )
    removed = clear_expired_overrides(datetime.fromisoformat("2026-07-24T10:00:00+08:00"))
    expired_payload = {
        "expired_override": expired.to_dict(),
        "removed_count": removed,
        "active_after_cleanup": get_active_override(
            "TWSE",
            "2026-07-25",
            as_of_time=datetime.fromisoformat("2026-07-24T10:00:00+08:00"),
        ),
        "ignored": True,
        "note": "Expired override is ignored and removed from process-local memory.",
    }
    return active_payload, expired_payload


def main() -> None:
    active_override, expired_override = _override_examples()
    examples = [
        ("Regular TWSE trading day", _context("2317", "2026-06-18T10:00:00+08:00")),
        ("TWSE holiday plus US regular session", _context("2317", "2026-06-19T22:30:00+08:00")),
        ("Saturday morning after US close", _context("2317", "2026-06-20T08:00:00+08:00")),
        (
            "TAIFEX night-session belongs_to_trade_date example",
            {
                "session_date": "2026-06-19",
                "belongs_to_trade_date": get_next_twse_trading_day_after("2026-06-19"),
                "note": "Uses current TWSE weekday/holiday heuristic; official calendar/override is future work.",
            },
        ),
        (
            "Active in-memory override changes TWSE status",
            active_override,
        ),
        (
            "Expired in-memory override is ignored",
            expired_override,
        ),
        (
            "Unavailable factor is not neutral",
            make_factor_freshness(
                factor="taifex",
                market="TAIFEX",
                freshness="unavailable",
                confidence="low",
                usable=False,
                data_quality="unavailable",
                reason="No TAIFEX data; not a neutral 50-point signal.",
            ).to_dict(),
        ),
        (
            "Holiday dampener compresses score amplitude only",
            {
                "normalized_score": 62,
                "holiday_dampener": 0.5,
                "final_score": apply_holiday_dampener(62, 0.5),
                "formula": "50 + (normalized_score - 50) * holiday_dampener",
            },
        ),
    ]

    out = [
        "# calendar_shadow_context_examples.md",
        "",
        "Generated by `scripts/export_calendar_shadow_context.py`.",
        "This file is debug documentation only and is not used by production.",
        "",
    ]
    for title, payload in examples:
        out.append(f"## {title}")
        out.append("")
        out.append("```json")
        out.append(json.dumps(payload, ensure_ascii=False, indent=2))
        out.append("```")
        out.append("")

    target = ROOT / "docs" / "calendar_shadow_context_examples.md"
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {target}")


if __name__ == "__main__":
    main()
